# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8080/api/user/insert
Content-Type: application/json

{
  "id": "a",
  "pw": "a",
  "name": "a"
}
###

GET http://localhost:8080/api/board/select
Accept: application/json

###

GET http://localhost:8080/api/board/totalGood/a
Accept: application/json

###

POST http://localhost:8080/api/board/insert
Content-Type: application/json

{
  "user_id": "a",
  "title": "30title",
  "content": "30ontent",
  "grade" : 1,
  "good" : 30
}
###
